### ISSUE TITLE
Header breaks view point returned from toc

### ISSUE THREAD

**Issue by NSq1** [g2forge/charcoal#11]
Hello, charcoal looks great but I have a small issue with header obstructing page elements after using TOC.

I describe this issue and potential steps in fixing it below.

- Issue
Whenever you use toc/url navigation like: www.g2forge.com/charcoal/#about-image 
Part of returned view point (and direct descendant) is obscured by page header (div#header).

- Expected behavior:
Returned view point after url navigation (/#name_of_target) should present said element unobstructed just under page header.

- Observed on:
Google Chrome Version 73.0.3683.10 (Official Build) dev (64-bit)
Microsoft Edge 44.17763.1.0

- Example fix:
```
window.addEventListener('hashchange', function(){
   document.documentElement.scrollTop = document.documentElement.scrollTop - $("div#header").height() - 5; 
}, false);
``` 
Number (static 5) is an extra spacing between header and top of navigated element for aesthetic purpose. Fix only targets TOC navigation, does not fix URL navigation (example: other site referring to #id)
I'm not sure if this issue can be fixed without use of JS

Edit: Rough fix with taking care of redirect from outside of the site issue
```
realignViewPoint = function() {
    if (window.location.href.indexOf("#") > 0) {
        document.documentElement.scrollTop = document.documentElement.scrollTop - $("div#header").height() - 5;
    }
}
window.addEventListener('hashchange', realignViewPoint, false);
window.addEventListener('load', realignViewPoint, false);
```

**Comment by gdgib** [comment]
Thanks for the report and suggested fix!  I've been less scrupulous about chrome and edge testing than I should. Give me a bit to see if I can find a non-JS solution.  Honestly, some of the CSS needs a little improvement in this area, and this is exactly the kick I need to do it.

**Comment by gdgib** [comment]
FWIW, also an issue on Firefox.  Sigh.  Thought I'd fixed this a while ago.

**Comment by gdgib** [comment]
Yeah, it looks like javascript is required since I can't change the HTML generated during a jekyll build without losing github pages compatability.  Sigh...

Thanks for the example code @NSq1.  I ended up with something similar.  Ended up a little more complex since the header isn't always fixed (e.g. on smaller screens).

**Comment by gdgib** [comment]
Upgrade to [charcoal 0.0.7](https://rubygems.org/gems/jekyll-theme-charcoal/versions/0.0.7).  Thanks for reporting and using the theme!
